apiVersion: v1
kind: Service
metadata:
  name: daemonset-svc-headless
spec:
  clusterIP: None
  selector:
    name: daemonset-communicate # select the damonset name
  ports:
    - protocol: TCP
      name: "http"
      port: 80
      targetPort: 80