apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  database_url: mongodb-service #this is actually the service name we created earlier
  mongodb-port: '27017' #this is actually the service name we created earlier
