apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-cpu
spec:
  selector:
    matchLabels:
      app: application-cpu
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: application-cpu
    spec:
      containers:
      - name: kangaphp
        image: filipkangalov/kangaphp:v1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "50Mi"
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "2000m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: application-cpu
spec:
  selector:
    app: application-cpu # the app name
  type: ClusterIP
  ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: 8080
