# Use the official PHP image with Nginx
# FROM php:latest
FROM trafex/php-nginx:latest

# Create a directory for the PHP application
WORKDIR /var/www/html

# Copy your PHP file to the container
COPY index.php /var/www/html/index.php